export const TYPES = {
  Application: Symbol.for("Application"),
  ILogger: Symbol.for("ILogger"),
  UserController: Symbol.for("UserController"),
  UserRepository: Symbol.for("UserRepository"),
  UserService: Symbol.for("UserService"),
  ReviewsController: Symbol.for(" ReviewsController"),
  ReviewsRepository: Symbol.for(" ReviewsRepository"),
  ReviewsService: Symbol.for(" ReviewsService"),
  ConsultantsController: Symbol.for("ConsultantsController"),
  ConsultantsRepository: Symbol.for("ConsultantsRepository"),
  ConsultantsService: Symbol.for("ConsultantsService"),
  TelegramController: Symbol.for("TelegramController"),
  TelegramRepository: Symbol.for("TelegramRepository"),
  TelegramService: Symbol.for("TelegramService"),
  CarController: Symbol.for("CarController"),
  CarRepository: Symbol.for("CarRepository"),
  CarService: Symbol.for("CarService"),
  ExeptionFilter: Symbol.for("ExeptionFilter"),
  ConfigService: Symbol.for("ConfigService"),
  PrismaService: Symbol.for("PrismaService"),
  PassportConfig: Symbol.for("PassportConfig"),
};
